### ISSUE TITLE
Unable to transfer rr sessions to other machines

### ISSUE THREAD

**Issue by pyoor** [rr-debugger/rr#3408]
Similar to https://github.com/rr-debugger/rr/issues/2643, I'm having issues recording rr sessions on AWS m5d (Intel(R) Xeon(R) Platinum 8259CL) instances and transferring them to other machines for processing.

```
root@8816d0375bd4:/home/worker# rr traceinfo /tmp/tmp7v5xz98r/
{
  "uuid":[128,112,84,118,2,72,126,109,180,42,18,195,230,75,15,233],
  "xcr0":767,
  "bindToCpu":38,
  "cpuidFaulting":true,
  "requiredForwardCompatibilityVersion":3,
  "ticksSemantics":"rcb",
  "cpuidRecords":[
    [0,4294967295,22,1970169159,1818588270,1231384169],
    [1,4294967295,329303,1648363520,1073675263,3219913727],
    [2,4294967295,1979933441,15775231,0,12779520],
    [3,4294967295,0,0,0,0],
    [4,0,2080391457,29360191,63,0],
    [4,1,2080391458,29360191,63,0],
    [4,2,2080391491,62914623,1023,0],
    [4,3,2081407331,41943103,53247,5],
    [4,4,0,0,0,0],
    [5,4294967295,64,64,3,8224],
    [6,4294967295,3831,2,9,0],
    [7,0,0,60356587,24,3154117632],
    [8,4294967295,0,0,0,0],
    [9,4294967295,0,0,0,0],
    [10,4294967295,120587268,0,0,1539],
    [11,0,1,2,256,98],
    [11,1,6,48,513,98],
    [11,2,0,0,2,98],
    [12,4294967295,0,0,0,0],
    [13,0,767,2696,2696,0],
    [13,1,14,2568,256,0],
    [13,2,256,576,0,0],
    [13,3,64,960,0,0],
    [13,4,64,1024,0,0],
    [13,5,64,1088,0,0],
    [13,6,512,1152,0,0],
    [13,7,1024,1664,0,0],
    [13,8,128,0,1,0],
    [13,9,8,2688,0,0],
    [13,10,0,0,0,0],
    [13,11,0,0,0,0],
    [13,12,0,0,0,0],
    [13,13,0,0,0,0],
    [13,14,0,0,0,0],
    [13,15,0,0,0,0],
    [13,16,0,0,0,0],
    [13,17,0,0,0,0],
    [13,18,0,0,0,0],
    [13,19,0,0,0,0],
    [13,20,0,0,0,0],
    [13,21,0,0,0,0],
    [13,22,0,0,0,0],
    [13,23,0,0,0,0],
    [13,24,0,0,0,0],
    [13,25,0,0,0,0],
    [13,26,0,0,0,0],
    [13,27,0,0,0,0],
    [13,28,0,0,0,0],
    [13,29,0,0,0,0],
    [13,30,0,0,0,0],
    [13,31,0,0,0,0],
    [13,32,0,0,0,0],
    [13,33,0,0,0,0],
    [13,34,0,0,0,0],
    [13,35,0,0,0,0],
    [13,36,0,0,0,0],
    [13,37,0,0,0,0],
    [13,38,0,0,0,0],
    [13,39,0,0,0,0],
    [13,40,0,0,0,0],
    [13,41,0,0,0,0],
    [13,42,0,0,0,0],
    [13,43,0,0,0,0],
    [13,44,0,0,0,0],
    [13,45,0,0,0,0],
    [13,46,0,0,0,0],
    [13,47,0,0,0,0],
    [13,48,0,0,0,0],
    [13,49,0,0,0,0],
    [13,50,0,0,0,0],
    [13,51,0,0,0,0],
    [13,52,0,0,0,0],
    [13,53,0,0,0,0],
    [13,54,0,0,0,0],
    [13,55,0,0,0,0],
    [13,56,0,0,0,0],
    [13,57,0,0,0,0],
    [13,58,0,0,0,0],
    [13,59,0,0,0,0],
    [13,60,0,0,0,0],
    [13,61,0,0,0,0],
    [13,62,0,0,0,0],
    [13,63,0,0,0,0],
    [14,4294967295,0,0,0,0],
    [15,0,0,207,0,2],
    [15,1,0,106496,207,7],
    [16,0,0,10,0,0],
    [16,1,10,1536,4,15],
    [16,3,89,0,4,7],
    [17,4294967295,0,0,0,0],
    [18,0,0,0,0,0],
    [19,4294967295,0,0,0,0],
    [20,0,1,15,7,0],
    [20,1,38338562,4145151,0,0],
    [21,4294967295,2,200,0,0],
    [22,4294967295,2500,3500,100,0],
    [2147483648,4294967295,2147483656,0,0,0],
    [2147483649,4294967295,0,0,289,739248128],
    [2147483650,4294967295,1702129225,693250156,1868912672,693250158],
    [2147483651,4294967295,1634488352,1970170228,842539117,1279473973],
    [2147483652,4294967295,1431323424,840974368,1194341678,31304],
    [2147483653,4294967295,0,0,0,0],
    [2147483654,4294967295,0,0,16801856,0],
    [2147483655,4294967295,0,0,0,256],
    [2147483656,4294967295,12334,0,0,0]
  ],
  "chaosMode":true,
  "exclusionRange": { "start": 70059654356992, "end": 74457700868096 },
[ERROR /home/roc/rr/rr/src/ExtraRegisters.cc:630:set_to_raw_data()] Feature 9 has wrong size 8, expected 0
[FATAL /home/roc/rr/rr/src/TraceStream.cc:594:read_frame()] Invalid extended register data in trace
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x41)[0x563a9e9dcab1]
rr(_ZN2rr15notifying_abortEv+0xe)[0x563a9e9e019e]
rr(+0x213aa2)[0x563a9ea13aa2]
rr(_ZN2rr11TraceReader10read_frameEv+0xec5)[0x563a9e9cde15]
rr(_ZN2rr13ReplaySession27advance_to_next_trace_frameEv+0x60)[0x563a9e96a750]
rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0x1ef)[0x563a9e9a005f]
rr(+0x1bb0fd)[0x563a9e9bb0fd]
rr(_ZN2rr16TraceInfoCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x9f)[0x563a9e9bb59f]
rr(main+0x5f0)[0x563a9e8baaf0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f7fa3f09083]
rr(_start+0x2a)[0x563a9e8bb0ea]
=== End rr backtrace
Aborted (core dumped)
```

**Comment by khuey** [comment]
This was fixed in #3362

**Comment by pyoor** [comment]
@khuey I'm still getting this on `rr version 5.6.git.20221129.026cef96 `

**Comment by khuey** [comment]
Idk what that is, that's not an rr version number.

roc's home directory being present in your error message strongly suggests you're using the 5.6.0 release that we published which does not contain #3362. I've also already talked to jkratzer about Mozilla's need for another release here.

**Comment by pyoor** [comment]
Sorry, we actually patch the version number to include the rev.  It was built earlier today on commit 026cef96.

**Comment by khuey** [comment]
Are you running the build you made yourself on the machine doing the replay?

**Comment by pyoor** [comment]
Yes.  The docker image is the same for the record and replay instances.  The only difference is one is bare metal and the other is a general compute instance.

**Comment by khuey** [comment]
Ok, what are the precise EC2 instance types you're recording on and replaying on?

**Comment by pyoor** [comment]
Recorded on an AWS m5d.metal instance, replayed on GCP n2-standard-4.

**Comment by khuey** [comment]
Oh. Is that GCP instance capable of replaying recordings that were recorded on it? Last I checked rr didn't work on GCP at all.

**Comment by pyoor** [comment]
I'm not sure but two things to note there; first we're only using the GCP instance to submit the trace with pernosco-submit, and second, I'm unable to use pernosco-submit using that same trace on my local machine.

**Comment by khuey** [comment]
Ok, I'll try to reproduce that and get back to you.

**Comment by pyoor** [comment]
Let me know if you need the actual trace.

**Comment by khuey** [comment]
When I run `rr traceinfo` on a GCP n2-standard-4 I get

`[FATAL src/PerfCounters.cc:308:start_counter()] Unable to open performance counter with 'perf_event_open'; are hardware perf events available? See https://github.com/rr-deb
ugger/rr/wiki/Will-rr-work-on-my-system`

which is what I would expect because afaik hardware performance counters are not available on GCP.

If I take two traces recorded with the 5.6.0 release and 026cef968a34ae2b3e272e7ac7b6c9c9f98261a0 respectively on an m5d.metal and move it to my local machine (which is a Core i7-6700K) then `rr traceinfo` with the rr from the 5.6.0 release fails on both traces in the way you describe and `rr traceinfo` with an rr built from 026cef968a34ae2b3e272e7ac7b6c9c9f98261a0 works on both traces as expected.

So my conclusions are:
1. It's the *replaying* rr that needs to be updated to fix this issue, not the recording rr.
2. I still think you are replaying with the old rr because a) that's the only way I can reproduce this and b) the /home/roc paths in the error messages you shared strongly suggest you're replaying with the release that roc built and not something you built yourself.
3. Even after this fix you're still not going to be able to run `rr traceinfo` on a GCP n2-standard-4 because of the lack of performance counters.

For that last bit, the thing in `rr traceinfo` that needs the performance counters is extracting the environment variables, which requires replaying to the first exec, and replaying needs the performance counters. pernosco-submit checks those environment variables against a deny list of "sensitive" environment variables (e.g. `AWS_SECRET_ACCESS_KEY`) and aborts the upload if they're found. We could add a mode to pernosco-submit and a corresponding command line option to `rr traceinfo` that skips this. The environment of your automation is presumably well known and won't contain these sorts of secrets.

**Comment by rocallahan** [comment]
Replaying to the first execve doesn't actually require perf counters since we don't check perf counter values and don't need to replay asynchronous events. We should just fix replay to support a "no perf counters" mode and make "rr traceinfo" use that.

**Comment by pyoor** [comment]
This doesn't appear to work for me.  I recorded a trace on the aws bare metal instance, pulled it to my local machine (non-virtualized).  When trying to run rr traceinfo on it, I get:
```
rr traceinfo ./
{
  "uuid":[218,192,48,219,54,55,71,179,29,80,29,109,28,33,181,141],
  "xcr0":767,
  "bindToCpu":37,
  "cpuidFaulting":true,
  "requiredForwardCompatibilityVersion":3,
  "ticksSemantics":"rcb",
  "cpuidRecords":[
    [0,4294967295,22,1970169159,1818588270,1231384169],
    [1,4294967295,329303,1614809088,1073675263,3219913727],
    [2,4294967295,1979933441,15775231,0,12779520],
    [3,4294967295,0,0,0,0],
    [4,0,2080391457,29360191,63,0],
    [4,1,2080391458,29360191,63,0],
    [4,2,2080391491,62914623,1023,0],
    [4,3,2081407331,41943103,53247,5],
    [4,4,0,0,0,0],
    [5,4294967295,64,64,3,8224],
    [6,4294967295,3831,2,9,0],
    [7,0,0,60356587,24,3154117632],
    [8,4294967295,0,0,0,0],
    [9,4294967295,0,0,0,0],
    [10,4294967295,120587268,0,0,1539],
    [11,0,1,2,256,96],
    [11,1,6,48,513,96],
    [11,2,0,0,2,96],
    [12,4294967295,0,0,0,0],
    [13,0,767,2696,2696,0],
    [13,1,14,2568,256,0],
    [13,2,256,576,0,0],
    [13,3,64,960,0,0],
    [13,4,64,1024,0,0],
    [13,5,64,1088,0,0],
    [13,6,512,1152,0,0],
    [13,7,1024,1664,0,0],
    [13,8,128,0,1,0],
    [13,9,8,2688,0,0],
    [13,10,0,0,0,0],
    [13,11,0,0,0,0],
    [13,12,0,0,0,0],
    [13,13,0,0,0,0],
    [13,14,0,0,0,0],
    [13,15,0,0,0,0],
    [13,16,0,0,0,0],
    [13,17,0,0,0,0],
    [13,18,0,0,0,0],
    [13,19,0,0,0,0],
    [13,20,0,0,0,0],
    [13,21,0,0,0,0],
    [13,22,0,0,0,0],
    [13,23,0,0,0,0],
    [13,24,0,0,0,0],
    [13,25,0,0,0,0],
    [13,26,0,0,0,0],
    [13,27,0,0,0,0],
    [13,28,0,0,0,0],
    [13,29,0,0,0,0],
    [13,30,0,0,0,0],
    [13,31,0,0,0,0],
    [13,32,0,0,0,0],
    [13,33,0,0,0,0],
    [13,34,0,0,0,0],
    [13,35,0,0,0,0],
    [13,36,0,0,0,0],
    [13,37,0,0,0,0],
    [13,38,0,0,0,0],
    [13,39,0,0,0,0],
    [13,40,0,0,0,0],
    [13,41,0,0,0,0],
    [13,42,0,0,0,0],
    [13,43,0,0,0,0],
    [13,44,0,0,0,0],
    [13,45,0,0,0,0],
    [13,46,0,0,0,0],
    [13,47,0,0,0,0],
    [13,48,0,0,0,0],
    [13,49,0,0,0,0],
    [13,50,0,0,0,0],
    [13,51,0,0,0,0],
    [13,52,0,0,0,0],
    [13,53,0,0,0,0],
    [13,54,0,0,0,0],
    [13,55,0,0,0,0],
    [13,56,0,0,0,0],
    [13,57,0,0,0,0],
    [13,58,0,0,0,0],
    [13,59,0,0,0,0],
    [13,60,0,0,0,0],
    [13,61,0,0,0,0],
    [13,62,0,0,0,0],
    [13,63,0,0,0,0],
    [14,4294967295,0,0,0,0],
    [15,0,0,207,0,2],
    [15,1,0,106496,207,7],
    [16,0,0,10,0,0],
    [16,1,10,1536,4,15],
    [16,3,89,0,4,7],
    [17,4294967295,0,0,0,0],
    [18,0,0,0,0,0],
    [19,4294967295,0,0,0,0],
    [20,0,1,15,7,0],
    [20,1,38338562,4145151,0,0],
    [21,4294967295,2,200,0,0],
    [22,4294967295,2500,3500,100,0],
    [2147483648,4294967295,2147483656,0,0,0],
    [2147483649,4294967295,0,0,289,739248128],
    [2147483650,4294967295,1702129225,693250156,1868912672,693250158],
    [2147483651,4294967295,1634488352,1970170228,842539117,1279473973],
    [2147483652,4294967295,1431323424,840974368,1194341678,31304],
    [2147483653,4294967295,0,0,0,0],
    [2147483654,4294967295,0,0,16801856,0],
    [2147483655,4294967295,0,0,0,256],
    [2147483656,4294967295,12334,0,0,0]
  ],
  "chaosMode":true,
  "exclusionRange": { "start": 4488812171264, "end": 8886858682368 },
[FATAL src/PerfCounters.cc:304:start_counter()] Permission denied to use 'perf_event_open'; are hardware perf events available? See https://github.com/rr-debugger/rr/wiki/Will-rr-work-on-my-system
```

**Comment by pyoor** [comment]
Just to confirm, this was tested on commit 0512e184 but on the record and replay machines.

**Comment by khuey** [comment]
21ebd077f34644434c83608ae8985e2e705de684 fixes that

**Comment by rocallahan** [comment]
I swear I tested that code :-(
